- hosts: all
  become: true
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config  # Adjusthe path if necessa
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /home/ubuntu/projet/Deployment.yml
     - name: delete old service
       command: kubectl delete -f /home/ubuntu/projet/Service.yml
     - name: create new deployment
       command: kubectl apply -f /home/ubuntu/projet/Deployment.yml
     - name: create new service
       command: kubectl apply -f /home/ubuntu/projet/Service.yml